@startuml
'https://plantuml.com/sequence-diagram
title Test1
actor Actor
boundary Boundary

entity Entity
database Database
collections Collections
autonumber 1.1
'第一个流程
activate Alice
activate Bob

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

==Foo==
autonumber stop

newpage Test2

autonumber 2.1

Alice -> Bob: Another authentication Request
control Control
Bob -> Control: 测试
deactivate Bob

activate Control
destroy Alice

Alice <-- Control: another authentication Response
||50||
activate Alice

activate Bob

queue queues

@enduml